---
title: Adjoint Systems, Left Null Space, and Row Space
subject: Vector Spaces and Bases
subtitle: leading to the fundamental thorem
short_title: Adjoint, Left Null and Row Space
authors:
  - name: Nikolai Matni
    affiliations:
      - Dept. of Electrical and Systems Engineering
      - University of Pennsylvania
    email: nmatni@seas.upenn.edu
license: CC-BY-4.0
keywords: transpose, adjoint, left null space, row spaces
math:
  '\vv': '\mathbf{#1}'
  '\bm': '\begin{bmatrix}'
  '\em': '\end{bmatrix}'
  '\R': '\mathbb{R}'
---

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/nikolaimatni/ese-2030/HEAD?labpath=/01_Vector_Spaces_and_Bases/036-adj.ipynb)

{doc}`Lecture notes <../lecture_notes/Lecture 04 - The Fundamental Matrix Subspaces (Kernel, Image, CoKernel, CoImage), Fundamental Theorem of Linear Algebra, and a brief interlude on the Matrix Transpose.pdf>`

## Reading

Material related to this page, as well as additional exercises, can be found in ALA Ch. 2.5.

## Learning Objectives

By the end of this page, you should know:
- what is the transpose of a matrix
- Adjoint systems
- Left Null Space
- Row Space
- the fundamental theorem of linear algebra and its implication

## Matrix Transpose

The transpose $A^{\top}$ of an $m \times n$ matrix $A$ is the $n \times m$ matrix obtained by interchanging its rows and columns. Hence, if $B = A^{\top}$, then $b_{ij} = a_{ji}$. 

:::{prf:example}
:label:tr_eg
1. If $A = \bm -1 & 8 \\ 5 & 7 \\ 2 & -5\em$, then $A^{\top} = \bm -1 & 5 & 2 \\ 8 & 7 & -5\em$.
2. Transpose of a row vector $\vv c^{\top} = \bm 3 & -1 & -2\em$ is a column vector $\vv c = \bm 3 \\ -1 \\ -2\em$.
:::

```{note} Properties
1. $\left(A^{\top}\right)^{\top} = A$ (Transpose of transpose brings back to original form) 
2. $(A + B)^{\top} = A^{\top} + B^{\top}$ (Transpose and addition commute)
3. $(AB)^{\top} = B^{\top}A^{\top}$ (Reverses order on products)
4. $\left(A^{-1}\right)^{\top} = \left(A^{\top}\right)^{-1} = A^{-T}$ (inverse and transpose commute, provided $A^{-1}$ exists)

A special case if the product of a row vector $\vv v^{\top}$ and a column vector $\vv w$ (which we will revisit):
\begin{equation}
\label{row_col}
\vv v^{\top} \vv w = \left(\vv v^{\top} \vv w\right)^{\top} = \vv w^{\top} \vv v,
\end{equation}
because the product in [](#row_col) is a scalar and the transpose of a scalar is itself.
```

In [19]:
## Transpose of matrices
import numpy as np

A = np.array([[-1, 8],
              [5, 7],
              [2, -5]])
AT = A.T # Transpose of the A matrix

c = np.array([[3, -1, -2]]) # row vector
cT = c.T

c1 = np.array([3, -1, -2]) # ?-vector
c1T = c1.T

print("Tranpose of \nA: \n", AT, "\nc: \n", cT, "\nc1: \n", c1T)

Tranpose of 
A: 
 [[-1  5  2]
 [ 8  7 -5]] 
c: 
 [[ 3]
 [-1]
 [-2]] 
c1: 
 [ 3 -1 -2]


## Adjoint System

This section explores the properties of the system of linear equations defined by $A^{\top}$.

:::{prf:definition} Adjoint System
:label: adj_defn
The _adjoint_ to a linear system $A \vv x = \vv b$ of $m$ equations in $n$ unknowns is the linear system 
\begin{equation}
\label{adj_eqn}
A^{\top} \vv y = \vv f
\end{equation}
consisting of $n$ equations in $m$ unknowns $\vv y \in \mathbb{R}^m$ with right-hand side $\vv f \in \mathbb{R}^n$.
:::

:::{prf:example}
:label:adj_eg
Consider the linear system $A \vv x = \vv b$ with
$$
A = \bm 1 & 5 & -2 & 2 \\ 0 & 1 & 2 & -5 \\ 1 & 3 & -3 & 7\em,
$$
which has the transpose 
$$
A^{\top} = \bm 1 & 0 & 1 \\ 5 & 1 & 3 \\ -2 & 2 & -3 \\ 2 & -5 & 7\em.
$$
Thus, the adjoint system $A^{\top} \vv y = \vv f$ is
$$
y_1 + y_2 &= f_1, \\
5y_1 + y_2 + 3y_3 &= f_2, \\
-2y_1 + 2y_2 - 3y_3 &= f_3, \\
2y_1 - 5y_2 + 7y_3 &= f_4.
$$
:::

We will see some surprising connections between the solutions of $A \vv x = \vv b$ and $A^{\top} \vv y = \vv f$ later in the course.



## Row Space and Left Null Space


:::{prf:definition} Row Space
:label: rows_defn
The _row space (coimage)_ of $A \in \mathbb{R}^{m \times n}$ is the column space of its transpose
\begin{equation}
\label{row_eqn}
\textrm{Row}(A) = \textrm{Col}(A^{\top}) = \{\vv f \in \mathbb{R}^n : \vv f = A^{\top} \vv y \ \textrm{for some} \ \vv y \in \mathbb{R}^m\} \subset \mathbb{R}^n
\end{equation}
:::
It is called the row space because it is the subspace of $\mathbb{R}^n$ spanned by the rows of $A$. 

:::{prf:definition} Left Null Space
:label: nulls_defn
The _left null space (cokernel)_ of $A \in \mathbb{R}^{m \times n}$ is the null space of its transpose
\begin{equation}
\label{nulls_eqn}
\textrm{LNull}(A) = \textrm{Null}(A^{\top}) = \{\vv w \in \mathbb{R}^m :  A^{\top} \vv w = \vv 0\} \subset \mathbb{R}^m
\end{equation}
:::
It is called the left null space of $A$ because LNull$(A)$ is composed of row vectors $\vv w^{\top}$ that satisfy $\vv w^{\top} A = \vv 0^{\top}$.


:::{prf:example} TO DO
:label:alls_eg
Single example for Col$(A)$, Null$(A)$, Row$(A)$, LNull$(A)$, and corresponding NumPy code.
:::

In [48]:
## Find the four fundamental subspaces of a matrix
from sympy import *

# A = Matrix([[0, -2, 1],
#             [0, -4, 2],
#             [1, -2, 1]])

A = Matrix([[1, 5, -2, 2],
            [0, 1, 2, -5],
            [1, 3, -3, 7]])

print("The A matrix:\n", A)

A_Null = A.nullspace()
A_col = A.columnspace()

print("Null space of A: \n", A_Null, "\nColumn space of A: \n", A_col)

AT = A.T

A_LNull = AT.nullspace()
A_row = AT.columnspace()

print("Left Null space of A: \n", A_LNull, "\nRow space of A: \n", A_row)

The A matrix:
 Matrix([[1, 5, -2, 2], [0, 1, 2, -5], [1, 3, -3, 7]])
Null space of A: 
 [Matrix([
[ -7],
[5/3],
[5/3],
[  1]])] 
Column space of A: 
 [Matrix([
[1],
[0],
[1]]), Matrix([
[5],
[1],
[3]]), Matrix([
[-2],
[ 2],
[-3]])]
Left Null space of A: 
 [] 
Row space of A: 
 [Matrix([
[ 1],
[ 5],
[-2],
[ 2]]), Matrix([
[ 0],
[ 1],
[ 2],
[-5]]), Matrix([
[ 1],
[ 3],
[-3],
[ 7]])]


## The Fundamental Theorem

The transpose $A^{\top}$ of an $m \times n$ matrix $A$ is the $n \times m$ matrix obtained by interchanging its rows and columns. Hence, if $B = A^{\top}$, then $b_{ij} = a_{ji}$. 

:::{prf:theorem} The Fundamental Theorem of Linear Algebra
:label:fund_thm
Let $A$ be an $m \times n$ matrix, and let $r$ be its rank. Then
\begin{equation}
\label{fund_thm_eqn}
\textrm{dim(Row}(A)) = \textrm{dim(Col}(A)) = \textrm{rank}(A) = \textrm{rank}(A^{\top}) = r, \\
\textrm{dim(Null}(A)) = n - r, \ \textrm{dim(LNull}(A)) = m-r.
\end{equation}
:::

The proof of [](#fund_thm) can be found in pp. 114-118 of ALA.


```{note} Observations from [](#fund_thm)
1. [Rank](../Linear_Algebraic_Systems/026-linsys-general.ipynb#rank_defn) is defined as the number of pivots, which coincides with the number of linearly independent columns of $A$. Hence, from [](#fund_thm), rank=number of linearly independent rows! 
2. Taking transposes does not affect the rank: rank is an intrinsic property of a matrix.
```

One implication of [](#fund_thm) is given below.

:::{prf:theorem} Rank-Nullity Theorem
:label:rank_null_thm
If $A \in \mathbb{R}^{m \times n}$, then
\begin{equation}
\label{rank_null_thm_eqn}
\textrm{dim(Col}(A)) + \textrm{dim(Null}(A)) = n, \ \textrm{where} \\
\textrm{dim(Col}(A)) = \textrm{rank}(A), \ \textrm{dim(Null}(A)) = \textrm{nullity}(A).
\end{equation}
:::
The statement in [](#rank_null_thm) holds true with Col$(A) \to$ Row$(A)$ and Null$(A) \to$ LNull$(A)$.

In [49]:
# Verifying Theorem-1

dim_col = len(A_col)
rank = A.rank()
dim_null = len(A_Null)
n_cols = A.shapev[1] # what is A.shape[0]?

print("Rank: ", rank, ". Dimension of column space is ", dim_col, "and null space is ", dim_null, 
      "\nNumber of columns n is ", n_cols)

Rank:  3 . Dimension of column space is  3 and null space is  1 
Number of columns n is  4


[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/nikolaimatni/ese-2030/HEAD?labpath=/01_Vector_Spaces_and_Bases/036-adj.ipynb)