---
title: General Linear Systems
subject:  Linear System of Equations
subtitle: solving with nonsingular coefficient matrices
short_title: General Linear Systems
authors:
  - name: Nikolai Matni
    affiliations:
      - Dept. of Electrical and Systems Engineering
      - University of Pennsylvania
    email: nmatni@seas.upenn.edu
license: CC-BY-4.0
keywords: inverse, Gauss Jordan elimination, identity matrix
---

## Reading
Material related to this page, as well as additional exercises, can be found in ALA Ch. 1.8.

## Learning Objectives

By the end of this page, you should know:
- row echelon form of matrices
- 

## Row echelon form

So far we have discussed techniques to solve only equations that have nonsingular coefficient matrices, since they always have a unique solution. Now, we move towards general systems that have $m$ equations and $n$ unknowns, including non-square ($m \neq n$) and singular coefficient matrices. We first define a generalized version of the upper triangular matrix as the _row echelon form_ of a matrix. 

```{prf:definition} Row echelon form
:label: row_echelon
A $m \times n$ matrix $U$ is said to be in _row echelon form_ if it has the following "staircase" structure:

:::{figure}../figures/02-row_echelon.jpg
:alt: Row echelon form
:width: 500px
:align: center
:::

The entries $\circledast$ are the _pivots_ that must be nonzero. The first $r$ rows of $U$ each contain exactly one pivot, but not all columns are required to include a pivot entry. The entries below the “staircase”, indicated by the solid line, are all zero, while the non-pivot
entries above the staircase, indicated by $*$, can be anything. The last $m − r$ rows are all zeros.
```

An example of a matrix in row echelon form is
\begin{equation}
\begin{bmatrix}
\textbf{2} & 0 & 1 & -5 & 6 \\
0 & 0 & \textbf{1} & 1 & 7 \\
0 & 0 & 0 & \textbf{-3} & 1\\
0 & 0 & 0 & 0 & 0
\end{bmatrix},
\end{equation}
where $r=3, m=4$ and the pivots are in $\textbf{bold}$

```{warning} Missing variables
In rare cases, a row echelon matrix could be
\begin{equation}
\label{rare_row_echelon}
\begin{bmatrix}
0 & 0 & \textbf{1} & -5 & 6 \\
0 & 0 & 0 & \textbf{3} & 10 \\
0 & 0 & 0 & 0 & \textbf{1}\\
0 & 0 & 0 & 0 & 0
\end{bmatrix},
\end{equation}
where the first two columns are all zeros. The matrix in [](#rare_row_echelon) corresponds to a linear system where the first two variables do not appear in any of the equations. Such systems almost never happen in real applications.
```

```{prf:theorem}
Every matrix can be reduced to row echelon form by a sequence of row operations ([scaling and adding](./023-linsys-gauuss.ipynb#rowop1), [swapping](./024-linsys-perms.ipynb#rowop2)).
```

```{note}Matrix notation
If $A$ is an $m \times n$ matrix, then we can find an $m \times m$ permutation matrix $P$ and an $m \times m$ lower triangular matrix $L$ such that 
$$
PA = LU,
$$
where $U$ is an $m \times n$ matrix in row echelon form. This is a generalized version of the permuted LU decomposition. 
```

For example, consider the linear system with the augmented matrix
\begin{equation}
\left[ \begin{array}{ccccc|c} 1 & 3 & 2 & -1 & 0 & a \\ 2 & 6 & 1 & 4 & 3 & b \\ -1 & -3 & -3 & 3 & 1 & c \\ 3 & 9 & 8 & 7 & 2 & d\end{array}\right],
\end{equation}
where $\textbf{b} = \begin{bmatrix} a \\ b \\ c \\ d\end{bmatrix}$ is a generic vector. The $(1,1)$ entry is a pivot. We use elementary row operations to make the entries below the pivot to be zero.
\begin{equation}
\label{no_pivot}
\left[ \begin{array}{ccccc|c} 1 & 3 & 2 & -1 & 0 & a \\ 0 & 0 & -3 & 6 & 3 & b-2a \\ 0 & 0 & -1 & 2 & 1 & c+a \\ 0 & 0 & 2 & 10 & 2 & d-3a\end{array}\right],
\end{equation}
In [](#no_pivot), the diagonal entry in the second row is zero. Hence, the pivot is the $(2, 3)^{rd}$ entry for the second row. This already is a generalized version of the upper triangular matrix we worked with previously. Continuing our process of making entries below the pivot to be zero, we get
\begin{equation}
\left[ \begin{array}{ccccc|c} 1 & 3 & 2 & -1 & 0 & a \\ 0 & 0 & -3 & 6 & 3 & b-2a \\ 0 & 0 & 0 & 0 & 0 & c-\frac{b}{3}+\frac{5}{3}a \\ 0 & 0 & 0 & 8 & 4 & d + \frac{2}{3}b-\frac{13}{3}a\end{array}\right].
\end{equation}
After swapping the last two rows, the left-hand matrix in row echelon form is
\begin{equation}
\left[ \begin{array}{ccccc|c} 1 & 3 & 2 & -1 & 0 & a \\ 0 & 0 & -3 & 6 & 3 & b-2a \\  0 & 0 & 0 & 8 & 4 & d + \frac{2}{3}b-\frac{13}{3}a \\ 0 & 0 & 0 & 0 & 0 & c-\frac{b}{3}+\frac{5}{3}a \end{array}\right].
\end{equation}
The three pivots are $1, -3, 8$ at $(1,1), (2, 3), (3, 4)$.

```{warning}
The pivots can only come from the coefficient matrix. Hence, the entries in the last column to the right side of the vertical line cannot be used as pivots since they are the right hand side of the equations.
```

## Rank of a matrix

```{prf:definition} Rank
The _rank_ of a matrix is the numer of pivots in its row echelon form.
```

Rank plays a central role in our study of linear algebra, but right now we will explore the connections between rank and the solution set of a linear system. 

```{note} Properties
1. For an $m \times n$ matrix $A$, we have $0 \leq r = \textnormal{rank}(A) \leq \min\{m, n\}$
2. The only matrix with zero rank is the zero matrix.
3. An $n \times n$ square matrix is nonsingular if and only if it has rank=$n$.
4. A matrix always has the same number of pivots even if we perform different row operations to reduce it to row echelon form.
```

In [5]:
## Row echelon form
import sympy
import numpy as np

# find the reduced row echelon form
A = sympy.Matrix([[1, 3, 2, -1, 0], [2, 6 ,1, 4, 3], [-1, -3, -3, 3, 1], [3, 9, 8, 7, 2]])
A_re = A.rref()

# find the rank of matrix
print("Row echelon form of the matrix:\n", A_re)

# find the rank of matrix
print("\nRank of the matrix: ", A.rank())

# Rank of a matrix using numpy
A_n = np.array([[1, 3, 2, -1, 0], [2, 6 ,1, 4, 3], [-1, -3, -3, 3, 1], [3, 9, 8, 7, 2]])
print("\nRank of the matrix using numpy: ", np.linalg.matrix_rank(A_n))

Row echelon form of the matrix:
 (Matrix([
[1, 3, 0, 0,  8/7],
[0, 0, 1, 0, -3/7],
[0, 0, 0, 1,  2/7],
[0, 0, 0, 0,    0]]), (0, 2, 3))

Rank of the matrix:  3

Rank of the matrix using numpy:  3


## Solving linear systems in row echelon form

```{tip}
The inverse of a matrix $A$ reverses the changes $A$ does to a vector $\textbf{x}$ via matrix-vector multiplication. 
$$
\textbf{x} \xrightarrow{A} A \textbf{x} \xrightarrow{A^{-1}} A^{-1}A\textbf{x} = \textbf{x}
$$
```

For example, the elementary operation of adding twice the first row to the third row is given by 

$$
E = \begin{bmatrix}1 & 0 & 0 \\ 0 & 1 & 0 \\ 2 & 0 & 1 \end{bmatrix},
$$
while the inverse operation is given by
$$
L = \begin{bmatrix}1 & 0 & 0 \\ 0 & 1 & 0 \\ -2 & 0 & 1 \end{bmatrix},
$$
and you can verify that $L = E^{-1}$. You can also verify similarly for permutation matrices with exactly one interchange 
$$
P = \begin{bmatrix} 0 & 1 & 0 \\ 1 & 0 & 0 \\ 0 & 0 & 1 \end{bmatrix} = P^{-1}.
$$

```{important}
A square matrix has an inverse if and only if it is nonsingular
```

The above statement will be proved later, but for now think about the scalar analogy. The equation $ax=b$ has a unique solution $x = a^{-1}b$ if and only if $a \neq 0$. Similarly, $A \textbf{x} = \textbf{b}$ has a unique solution $\textbf{x} = A^{-1}\textbf{b}$ if and only if $A^{-1}$ exists.

```{note} Properties
1. The inverse of a square matrix, if it exists, is unique.
2. If $A$ is invertible, so is $A^{-1}$ and $\left(A^{-1}\right)^{-1} = A$.
3. If $A$ and $B$ are invertible matrices of the same size, then their product $AB$ is also invertible, and
$$
(AB)^{-1} = B^{-1}A^{-1} \\ \textbf{order is reversed!}
$$
We have to undo transformations in the right order.
$$
\textbf{x} \xrightarrow{B} B \textbf{x} \xrightarrow{A} AB\textbf{x} \xrightarrow{A^{-1}} A^{-1}AB\textbf{x} = B\textbf{x} \xrightarrow{B^{-1}} B^{-1}B\textbf{x} = \textbf{x}
$$
```

## Worked examples

````{exercise}  TODO
:label: row-reduce-ex1
Write me
:::{hint} Click me for a hint!
:class: dropdown
Write me

:::
```{solution} my-exercise
:class: dropdown
Write me
```
````

````{exercise}  TODO
:label: row-reduce-ex1
Write me
:::{hint} Click me for a hint!
:class: dropdown
Write me

:::
```{solution} my-exercise
:class: dropdown
Write me
```
````

In [1]:
# Matrix inverse

import numpy as np
from scipy.linalg import lu

A_2 = np.array([[1, 2],
              [0, -1]])

A = np.array([[1, 2, 0],
              [0, 1, 0],
              [0, -3, 1]])

A_2_inv = np.linalg.inv(A_2)
A_inv = np.linalg.inv(A)
print("A_2_inv: \n", A_2_inv, "\nA_inv: \n", A_inv)
print("\nChecking inverses: \n", A_2_inv @ A_2, "\n", A @ A_inv)

A_2_inv: 
 [[ 1.  2.]
 [-0. -1.]] 
A_inv: 
 [[ 1. -2.  0.]
 [-0.  1. -0.]
 [ 0.  3.  1.]]

Checking inverses: 
 [[1. 0.]
 [0. 1.]] 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
# Inverse of the product

B = np.array([[1, 2, 0],
              [0, 3, 0],
              [1, -3, 1]])

B_inv = np.linalg.inv(B)

AB_inv = np.linalg.inv(A@B)
print("\nInverse of product: \n", AB_inv, "\nProduct of inverses:\n", B_inv @ A_inv)


Inverse of product: 
 [[ 1.         -2.66666667  0.        ]
 [-0.          0.33333333 -0.        ]
 [-1.          6.66666667  1.        ]] 
Product of inverses:
 [[ 1.         -2.66666667  0.        ]
 [ 0.          0.33333333  0.        ]
 [-1.          6.66666667  1.        ]]


## Gauss Jordan Elimination

Gauss Jordan Elimination (GJE) is the principal algorithm for computing inverses of a nonsingular matrix. 

```{important}
For a square matrix $A$, we only need to solve the _right inverse_ $AX = I$, since the _left inverse_ $XA = I$ is an automatic consequence.
```

```{note}
Some matrices may satsify only one of the two conditions: either a right inverse $AX = I$ or a left inverse $XA = I$. For a non-square matrix, the same $X$ cannot satisfy $AX = XA = I$ (check dimensions). Hence, we emphasize that for $X$ to be an inverse of $A$, both left and right inverse conditions should be satisfied. 
```

We focus on the identity matrix which is the result after multiplying a matrix with its inverse. We define the $n \times 1$ _unit vectors_ $\textbf{e}_i$:
$$
\textbf{e}_1 = \begin{bmatrix} 1 \\ 0 \\ 0 \\ \vdots \\ 0 \end{bmatrix}, \ \textbf{e}_2 = \begin{bmatrix} 0 \\ 1 \\ 0 \\ \vdots \\ 0 \end{bmatrix}, \cdots, \ \textbf{e}_n = \begin{bmatrix} 0 \\ 0 \\ \vdots \\ 1 \end{bmatrix}
$$
as the vectors with exactly one entry of $1$ in the $i^{th}$ position and zeros elsewhere. The vectors $\textbf{e}_i$ are the columns of the identity matrix $I_n$:
$$
I_n = \begin{bmatrix} \textbf{e}_1 & \textbf{e}_2 & \cdots & \textbf{e}_n \end{bmatrix}
$$
Hence, the right inverse equation can be written as
$$
AX = I \Leftrightarrow A \begin{bmatrix} \textbf{x}_1 & \textbf{x}_2 & \cdots & \textbf{x}_n \end{bmatrix} = \begin{bmatrix} \textbf{e}_1 & \textbf{e}_2 & \cdots & \textbf{e}_n \end{bmatrix} \Leftrightarrow A\textbf{x}_1 = \textbf{e}_1, A\textbf{x}_2 = \textbf{e}_2, \cdots, A\textbf{x}_n = \textbf{e}_n
$$

The above set of $n$ linear system of equations have the same coefficient matrix $A$ and hence we can construct the following large augmented matrix $M$.
\begin{equation}
\label{big_augm}
M = \left[ \begin{array}{c|ccc} A & \textbf{e}_1 & \textbf{e}_2 & \cdots & \textbf{e}_n  \end{array}\right] = \left[ \begin{array}{c|c} A & I  \end{array}\right].
\end{equation}

Applying row operations ([scaling and adding](./023-linsys-gauuss.ipynb#rowop1), [swapping](./024-linsys-perms.ipynb#rowop2)) to [](#big_augm), we can reduce to upper triangular form
$$
M = \left[ \begin{array}{c|c} A & I  \end{array}\right] \leftrightarrow N = \left[ \begin{array}{c|c} U & C  \end{array}\right].
$$
Then, we can solve the below set of $n$ linear systems via back substitution.
$$
U\textbf{x}_1 = \textbf{c}_1, U\textbf{x}_2 = \textbf{c}_2, \cdots, U\textbf{x}_n = \textbf{c}_n
$$

For example, consider the following $A$ matrix and the corresponding upper triangular form
\begin{equation}
\label{U_I}
A = \begin{bmatrix}0 & 2 & 1 \\ 2 & 6 & 1 \\ 1 & 1 & 4 \end{bmatrix} \Rightarrow M =  
\left[ \begin{array}{ccc|ccc} 0 & 2 & 1 & 1 & 0 & 0 \\ 2 & 6 & 1 & 0 & 1 & 0 \\ 1 & 1 & 4 & 0 & 0 & 1 \end{array}\right] \leftrightarrow N = \left[ \begin{array}{ccc|ccc} 2 & 6 & 1 & 0 & 1 & 0 \\ 0 & 2 & 1 & 1 & 0 & 0 \\ 0 & 0 & \frac{9}{2} & 1 & -\frac{1}{2} & 1 \end{array}\right].
\end{equation}
A mot common version of GJE continues to apply row operations and fully reduce the augmented matrix to the form $\left[ \begin{array}{c|c} I & X  \end{array}\right]$ so that $X$ is the inverse of $A$. However, in our current form $\left[ \begin{array}{c|c} U & C  \end{array}\right] $, the diagonal pivots of $U$ are not $1$. 
```{prf:observation} Elementary Row Operation \#3
:label: rowop3
Multiplying a row of the augmented matrix by a nonzero scalar yields an equivalent linear system.
```
The [scaling operation](#rowop3) on $N$ in [](#U_I) reduces the augmented matrix to
\begin{equation}
\label{V}
N = \left[ \begin{array}{ccc|ccc} 2 & 6 & 1 & 0 & 1 & 0 \\ 0 & 2 & 1 & 1 & 0 & 0 \\ 0 & 0 & \frac{9}{2} & 1 & -\frac{1}{2} & 1 \end{array}\right] \leftrightarrow \left[ \begin{array}{c|c} V & B \end{array}\right] = \left[ \begin{array}{ccc|ccc} 1 & 3 & \frac{1}{2} & 0 & \frac{1}{2} & 0 \\ 0 & 1 & \frac{1}{2} & \frac{1}{2} & 0 & 0 \\ 0 & 0 & 1 & \frac{2}{9} & -\frac{1}{9} & \frac{2}{9} \end{array}\right],
\end{equation}

where we divide each row by its corresponding pivot. Now, to make $V$ identity, we perform row operations starting from $(2, 3)$ since we need to make the upper triangular entries $0$.
\begin{equation}
\label{I_X}
\left[ \begin{array}{c|c} V & B \end{array}\right] = \left[ \begin{array}{ccc|ccc} 1 & 3 & \frac{1}{2} & 0 & \frac{1}{2} & 0 \\ 0 & 1 & \frac{1}{2} & \frac{1}{2} & 0 & 0 \\ 0 & 0 & 1 & \frac{2}{9} & -\frac{1}{9} & \frac{2}{9} \end{array}\right] \leftrightarrow \left[ \begin{array}{ccc|ccc} 1 & 0 & 0 & -\frac{23}{18} & \frac{7}{18} & \frac{2}{9} \\ 0 & 1 & 0 & \frac{7}{18} & \frac{1}{18} & -\frac{1}{9} \\ 0 & 0 & 1 & \frac{2}{9} & -\frac{1}{9} & \frac{2}{9} \end{array}\right]
\end{equation}
Finally, the right-hand matrix in [](#I_X) is the inverse of $A$:
$$
A^{-1} = \left[ \begin{array}{ccc}  -\frac{23}{18} & \frac{7}{18} & \frac{2}{9} \\  \frac{7}{18} & \frac{1}{18} & -\frac{1}{9} \\  \frac{2}{9} & -\frac{1}{9} & \frac{2}{9} \end{array}\right]
$$

:::{hint} Think!
:class: dropdown
What is the [elementary matrix](./023a-linsys-LU.ipynb#elementary) corresponding to the [scaling operation](#row-op3)? Start from the identity matrix as before.