---
title: 2.6 Adjoint Systems, Left Null Space, and Row Space
subject: Vector Spaces and Bases
subtitle:  More matrix subspaces
short_title: 2.6 Adjoint, Left Null and Row Space
authors:
  - name: Nikolai Matni
    affiliations:
      - Dept. of Electrical and Systems Engineering
      - University of Pennsylvania
    email: nmatni@seas.upenn.edu
license: CC-BY-4.0
keywords: transpose, adjoint, left null space, row spaces
math:
  '\vv': '\mathbf{#1}'
  '\bm': '\begin{bmatrix}'
  '\em': '\end{bmatrix}'
  '\R': '\mathbb{R}'
---

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/nikolaimatni/ese-2030/HEAD?labpath=/01_Ch_2_Vector_Spaces_and_Bases/036-adj.ipynb)

{doc}`Lecture notes <../lecture_notes/Lecture 04 - The Fundamental Matrix Subspaces (Kernel, Image, CoKernel, CoImage), Fundamental Theorem of Linear Algebra, and a brief interlude on the Matrix Transpose.pdf>`

## Reading

Material related to this page, as well as additional exercises, can be found in ALA Ch. 2.5.

## Learning Objectives

By the end of this page, you should know:
- the transpose of a matrix
- Adjoint systems
- Left Null Space
- Row Space
- the fundamental theorem of linear algebra and its implication

## Matrix Transpose

The transpose $A^{\top}$ of an $m \times n$ matrix $A$ is the $n \times m$ matrix obtained by interchanging its rows and columns. Hence, if ${B = A^{\top}}$, then $b_{ij} = a_{ji}$. 

:::{prf:example}
:label:tr_eg
1. If $A = \bm 1 & 2 & 3 \\ 4 & 5 & 6\em$, then $A^{\top} = \bm 1 & 4 \\ 2 & 5 \\ 3 & 6\em$.
2. Transpose of a column vector $\vv c = \bm 1 & 2 & 3\em$ gives a row vector $\vv c^{\top} = \bm 1 \\ 2 \\ 3\em$.
:::

```{note} Properties
1. $\left(A^{\top}\right)^{\top} = A$ (Transpose of transpose brings back to where you started) 
2. $(A + B)^{\top} = A^{\top} + B^{\top}$ (Transpose and addition commute)
3. $(AB)^{\top} = B^{\top}A^{\top}$ (Reverses order on products)
4. $\left(A^{-1}\right)^{\top} = \left(A^{\top}\right)^{-1} = A^{-T}$ (inverse and transpose commute, provided $A^{-1}$ exists)

A special case is the product of a row vector $\vv v^{\top}$ and a column vector $\vv w$ (which we will revisit):
\begin{equation}
\label{row_col}
\vv v^{\top} \vv w = \left(\vv v^{\top} \vv w\right)^{\top} = \vv w^{\top} \vv v,
\end{equation}
because the product in [](#row_col) is a scalar and the transpose of a scalar is itself.
```

#### Python Break!

Transpose of a NumPy array `A` is given by `A.T`. Below are examples of matrix (and vector) transposes using NumPy.

In [4]:
## Transpose of NumPy arrays
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])
AT = A.T # Transpose of the A matrix

c = np.array([[1],
              [2],
              [3]]) # column vector
cT = c.T # transpose of a column vector

c1 = np.array([1, 2, 3]) # ?-vector
c1T = c1.T

print("Tranpose of \nA: \n", AT, "\nc: \n", cT, "\nc1: \n", c1T)

Tranpose of 
A: 
 [[1 4]
 [2 5]
 [3 6]] 
c: 
 [[1 2 3]] 
c1: 
 [1 2 3]


## Adjoint System

This section explores the properties of the system of linear equations defined by $A^{\top}$, rather than $A$. This _adjoint system_ might first appear as some abstract nonsense that only mathematicians care about, but we will show that is has very practical consequences and interpretations. 

:::{prf:definition} Adjoint System
:label: adj_defn
The _adjoint_ to a linear system $A \vv x = \vv b$ of $m$ equations in $n$ unknowns is the linear system 
\begin{equation}
\label{adj_eqn}
A^{\top} \vv y = \vv f
\end{equation}
consisting of $n$ equations in $m$ unknowns $\vv y \in \mathbb{R}^m$ with Right-Hand Side (RHS) $\vv f \in \mathbb{R}^n$.
:::

:::{prf:example}
:label:adj_eg
Consider the linear system $A \vv x = \vv b$ with
$$
A = \bm 1 & -3 & 7 & 9 \\ 0 & 1 & 5 & -3 \\ 1 & -2 & -2 & 6\em,
$$
which has the transpose 
$$
A^{\top} = \bm 1 & 0 & 1 \\ -3 & 1 & -2 \\ 7 & 5 & -2 \\ 9 & -3 & 6\em.
$$
Thus, the adjoint system $A^{\top} \vv y = \vv f$ is
$$
y_1 + y_3 &= f_1, \\
-3y_1 + y_2- 2y_3 &= f_2, \\
7y_1 + 5y_2 - 2y_3 &= f_3, \\
9y_1 - 3y_2 + 6y_3 &= f_4.
$$
:::

At first glance, the solutions to $A \vv x = \vv b$ and the solutions to its adjoint $A^{\top} \vv y = \vv f$ seem unrelated. We will see some very surprising connections between them that will be revisited in even greater depth later in the course.



## Row Space and Left Null Space


:::{prf:definition} Row Space
:label: rows_defn
The _row space (coimage)_ of $A \in \mathbb{R}^{m \times n}$ is the column space of its transpose
\begin{equation}
\label{row_eqn}
\textrm{Row}(A) = \textrm{Col}(A^{\top}) = \{\vv f \in \mathbb{R}^n : \vv f = A^{\top} \vv y \ \textrm{for some} \ \vv y \in \mathbb{R}^m\} \subset \mathbb{R}^n
\end{equation}
:::
It is called the row space because it is the subspace of $\mathbb{R}^n$ spanned by the rows of $A$. 

:::{prf:definition} Left Null Space
:label: nulls_defn
The _left null space (cokernel)_ of $A \in \mathbb{R}^{m \times n}$ is the null space of its transpose
\begin{equation}
\label{nulls_eqn}
\textrm{LNull}(A) = \textrm{Null}(A^{\top}) = \{\vv w \in \mathbb{R}^m :  A^{\top} \vv w = \vv 0\} \subset \mathbb{R}^m
\end{equation}
:::
It is called the left null space of $A$ because LNull$(A)$ is composed of row vectors $\vv w^{\top}$ that satisfy $\vv w^{\top} A = \vv 0^{\top}$.


:::{prf:example} Finding the kernel, image, cokernel, and coimage of a $3\times 4$ matrix
:label:alls_eg

Consider the $3\times 4$ matrix:

\begin{align*}
    A = \bm 
        1 & 5 & -2 & 2 \\
        0 & 1 & 2 & -5 \\
        1 & 3 & -3 & 7
    \em
\end{align*}

Let's find its four fundamental subspaces (i.e., give bases for these subspaces), using hand and via the ``sympy`` Python package (it's also straightforward to do this in ``numpy``).

**Finding the nullspace/kernel.** The nullspace is the solution to the homogenous system:

\begin{align*}
    A \vv x = \bm 
        1 & 5 & -2 & 2 \\
        0 & 1 & 2 & -5 \\
        1 & 3 & -3 & 7
    \em \vv x = \vv 0.
\end{align*}

We apply the usual method of Gauss-Jordan elimination to find a reduced row echelon form of $A$, given by the equivalent augmented matrix:

\begin{align*}
    \left[\begin{array}{cccc|c}
        1 & 0 & 0 & 7 & 0 \\
        0 & 1 & 0 & -5/3 & 0 \\
        0 & 0 & 1 & -5/3 & 0
    \end{array}\right].
\end{align*}

which has basic variables $\vv{x_1}, \vv{x_2}, \vv{x_3}$ and free variable $\vv{x_4}$. The number of free variables, 1, is the dimension of the kernel. Solving this, we get:

\begin{align*}
    \vv{x_1} = -7 \vv{x_4}, \quad \vv{x_2} = \frac 5 3 \vv{x_4}, \quad \vv{x_3} = \frac 5 3 \vv{x_4}.
\end{align*}

meaning that a basis for the kernel is given by $\left\{ \bm -7 \\ 5/3 \\ 5/3 \\ 1 \em \right\}$.

**Finding the columnspace/image.** To find a basis for the image of $A$, we perform Gaussian elimination on $A^\top = \left[\begin{array}{ccc}
        1 & 0 & 1 \\
        5 & 1 & 3 \\
        -2 & 2 & -3\\
        2 & -5 & 7
\end{array}\right]$. To gain an initial intuition for this procedure, note that performing *row operations* on $A^\top$ is equivalent to performing *column operations*, which preserve the columnspace of $A$, on $A$. We get the equivalent matrix:

\begin{align*}
\bm
    1 & 0 & 1 \\
    0 & 1 & -2 \\
    0 & 0 & 3\\
    0 & 0 & 0
\em.
\end{align*}

A basis for $\text{Col}(A)$ is given by $\left\{ \bm 1\\0\\1\em, \bm 0\\1\\-2\em, \bm 0\\0\\3\em\right\}$. To see why, we know that:

\begin{align*}
    \text{span} \left\{ \bm 1\\0\\1\em, \bm 0\\1\\-2\em, \bm 0\\0\\3\em \right\} = \text{Col}(A)
\end{align*}

simply because column operations on $A$ preserve its columnspace. Furthermore, its clear that these three vectors are linearly independent. These two facts together imply that this set is a basis for $\text{Col}(A)$.

**Finding the left nullspace/cokernel.** The left nullspace is the solution to the homogenous system:

\begin{align*}
    A^\top \vv y = \bm 
        1 & 0 & 1 \\
        5 & 1 & 3 \\
        -2 & 2 & -3\\
        2 & -5 & 7
    \em \vv y = \vv 0.
\end{align*}

We apply the usual method of Gauss-Jordan elimination to find a reduced row echelon form of the augmented matrix, given by the equivalent augmented matrix:

\begin{align*}
    \left[\begin{array}{ccc|c}
        1 & 0 & 0 & 0 \\
        0 & 1 & 0 & 0 \\
        0 & 0 & 1 & 0\\
        0 & 0 & 0 & 0
    \end{array}\right].
\end{align*}

which has basic variables $\vv{y_1}, \vv{y_2}, \vv{y_3}$, and no free variables, meaning that the left nullspace of $A$ is trivial, $\text{LNull}(A) = \{\vv 0\}$.

**Finding the rowspace/coimage.** To find a basis for the rowspace of $A$, we perform Gaussian elimination on $A$, and get the equivalent matrix:

\begin{align*}
\bm
    1 & 5 & -2 & 2 \\
    0 & 1 & 2 & -5 \\
    0 & 0 & 3 & -5
\em.
\end{align*}

And hence a basis for $\text{Row}(A)$ is given by $\left\{ \bm 1\\5\\-2\\2\em, \bm 0\\1\\2\\-5\em, \bm 0\\0\\3\\-5\em\right\}$.
:::

In [48]:
## Find the four fundamental subspaces of a matrix
from sympy import *

A = Matrix([[1, 5, -2, 2],
            [0, 1, 2, -5],
            [1, 3, -3, 7]])

print("The A matrix:\n", A)

A_Null = A.nullspace()
A_col = A.columnspace()

print("Null space of A: \n", A_Null, "\nColumn space of A: \n", A_col)

AT = A.T

A_LNull = AT.nullspace()
A_row = AT.columnspace()

print("Left Null space of A: \n", A_LNull, "\nRow space of A: \n", A_row)

The A matrix:
 Matrix([[1, 5, -2, 2], [0, 1, 2, -5], [1, 3, -3, 7]])
Null space of A: 
 [Matrix([
[ -7],
[5/3],
[5/3],
[  1]])] 
Column space of A: 
 [Matrix([
[1],
[0],
[1]]), Matrix([
[5],
[1],
[3]]), Matrix([
[-2],
[ 2],
[-3]])]
Left Null space of A: 
 [] 
Row space of A: 
 [Matrix([
[ 1],
[ 5],
[-2],
[ 2]]), Matrix([
[ 0],
[ 1],
[ 2],
[-5]]), Matrix([
[ 1],
[ 3],
[-3],
[ 7]])]


## The Fundamental Theorem

The transpose $A^{\top}$ of an $m \times n$ matrix $A$ is the $n \times m$ matrix obtained by interchanging its rows and columns. Hence, if $B = A^{\top}$, then $b_{ij} = a_{ji}$. 

:::{prf:theorem} The Fundamental Theorem of Linear Algebra
:label:fund_thm
Let $A$ be an $m \times n$ matrix, and let $r$ be its rank. Then
\begin{equation}
\label{fund_thm_eqn}
\textrm{dim(Row}(A)) = \textrm{dim(Col}(A)) = \textrm{rank}(A) = \textrm{rank}(A^{\top}) = r, \\
\textrm{dim(Null}(A)) = n - r, \ \textrm{dim(LNull}(A)) = m-r.
\end{equation}
:::

The proof of [](#fund_thm) can be found in pp. 114-118 of ALA.


```{note} Observations from [](#fund_thm)
1. [Rank](../Linear_Algebraic_Systems/026-linsys-general.ipynb#rank_defn) is defined as the number of pivots, which coincides with the number of linearly independent columns of $A$. Hence, from [](#fund_thm), rank=number of linearly independent rows! 
2. Taking transposes does not affect the rank: rank is an intrinsic property of a matrix.
```

One implication of [](#fund_thm) is given below.

:::{prf:theorem} Rank-Nullity Theorem
:label:rank_null_thm
If $A \in \mathbb{R}^{m \times n}$, then
\begin{equation}
\label{rank_null_thm_eqn}
\textrm{dim(Col}(A)) + \textrm{dim(Null}(A)) = n, \ \textrm{where} \\
\textrm{dim(Col}(A)) = \textrm{rank}(A), \ \textrm{dim(Null}(A)) = \textrm{nullity}(A).
\end{equation}
:::
The statement in [](#rank_null_thm) holds true with Col$(A) \to$ Row$(A)$ and Null$(A) \to$ LNull$(A)$.

In [49]:
# Verifying Theorem-1

dim_col = len(A_col)
rank = A.rank()
dim_null = len(A_Null)
n_cols = A.shapev[1] # what is A.shape[0]?

print("Rank: ", rank, ". Dimension of column space is ", dim_col, "and null space is ", dim_null, 
      "\nNumber of columns n is ", n_cols)

Rank:  3 . Dimension of column space is  3 and null space is  1 
Number of columns n is  4


[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/nikolaimatni/ese-2030/HEAD?labpath=/01_Ch_2_Vector_Spaces_and_Bases/036-adj.ipynb)