---
title: Matrices and Vectors
subject:  Linear Algebraic Systems
subtitle: The building blocks of linear algebra
short_title: Matrices and Vectors
authors:
  - name: Nikolai Matni
    affiliations:
      - Dept. of Electrical and Systems Engineering
      - University of Pennsylvania
    email: nmatni@seas.upenn.edu
license: CC-BY-4.0
keywords: matrices, vectors, matrix arithmetic, matrix multiplication
math:
  '\vv': '\mathbf{#1}'
  '\bm': '\begin{bmatrix}'
  '\em': '\end{bmatrix}'
  '\R': '\mathbb{R}'
---

## Reading
Material related to this page, as well as additional exercises, can be found in ALA Ch. 1.2, LAA Ch 2.1, and ILA Ch. 2.4.  These notes are mostly based on ALA Ch 1.2 and LAA Ch 2.1.

## Learning Objectives

By the end of this page, you should know:
- what are matrices and vectors
- what arithmetic operations are allowed when working with matrices and vectors
- how to perform arithmetic operations on matrices and vectors
- how to represent linear system of equations using matrices and vectors

## Matrices and Vectors
A _matrix_ is a rectangular array of numbers.  For example
\begin{equation}
\begin{bmatrix} 1 & 0 & 3 \\ -2 & 4 & 1 \end{bmatrix}, \quad \begin{bmatrix} \pi & 0 \\ e & \frac{1}{2} \\ -1 & 0.83 \\ \sqrt{5} & -\frac{4}{7} \end{bmatrix}, \quad \begin{bmatrix} 0 & 0 & 0 \end{bmatrix}
\end{equation}
are all examples of matrices.  We use the notation
\begin{equation}
\label{matrix}
A = 
\begin{bmatrix} 
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}
\end{equation}
for a generic matrix $A$ of size $m \times n$ (read "$m$ by $n$"), where $m$ denotes the number of _rows_ in $A$ and $n$ denotes the number of _columns_[^cols].  Therefore, the preceding examples of matrices have respective sizes $2 \times 3$, $4 \times 2$, and $1 \times 3$.  A matrix is _square_ if $m=n$, i.e., it has the same number of rows as columns.  A _column vector_ is an $m \times 1$ matrix, while a _row vector_ is a $1 \times n$ matrix.  While these might seem like they are the same thing, they very much are not!  Column vectors end up playing a much more important role in our story, and so whenever we just say "vector" we will always mean a column vector.  A $1 \times 1$ matrix, which has a single entry, is both a column and row vector, and as we'll see later, behaves like an ordinary _scalar_ number.

The number that lies in the $i$th row and $j$th column of $A$ is called the $(i,j)$ _entry_ of $A$, and is denoted by $a_{ij}$.  The row index always appears first and the column index second.  Each column of $A$ is a $m \times 1$ vector, which we denote by $\vv a_1, \dots \vv a_n$. It will often be convenient to write a matrix in terms of its columns:
```{math}
:label: colmat
A = \begin{bmatrix} \vv a_1 & \vv a_2 & \cdots & \vv a_n \end{bmatrix}
```
```{note}
We will consistently use bold face lower case letters to denote vectors, and ordinary capital letters to denote matrices.
```
[^cols]: It is not a coincidence that $n$ is also the letter that we used for the number of unknowns in a [linear equation](./021-linsys-gauss.ipynb#lin-eq)! 


[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/nikolaimatni/ese-2030/HEAD?labpath=022-linsys-matvec.ipynb)

In [1]:
# Constructing matrices and vectors

import numpy as np

# a matrix A of size 2x3
A = np.array([[1, 2, 3],
             [4, 5, 6]])
# a matrix b of size 1x4 (row-vector)
b = np.array([[0, -1, 1, 3]])
# a matrix c of size 3x1 (column-vector)
c = np.array([[0],
              [1],
              [2]])

## Matrix Arithmetic

Matrix arithmetic involves three basic operations: _matrix addition_, _scalar multiplication_, and _matrix multiplication_. 

### Matrix Addition
First we define _addition_ of matrices.  You are allowed to add two matrices only if they are of the _same size_, and matrix addition is performed entry-wise.  For example
$$
\bm 1 & 2 \\ -1 & 0\em + \bm 3 & -5 \\ 2 & 1 \em = \bm 4 & -3 \\ 1 & 1 \em.
$$
More generally, if $A$ and $B$ are $m \times n$ matrices, then their sum $C = A+ B$ is the $m \times n$ matrix whose entries are given by $c_{ij} = a_{ij} + b_{ij}$ for $i=1,\dots,m$ and $j=1,\dots,n$.  When defined, matrix addition behaves just like ordinary addition. It is
1. commutative: $A + B = B + A$, and
2. associative: $A + (B + C) = (A+ B) + C = A + B + C$.

````{exercise}  Matrix addition
:label: matrix-addition-ex1

For (a)-(e), we are given some matrices. If they can be added together, then find their sum. Otherwise, indicate that they can't be added.

a. $\begin{bmatrix} 1 & 2 \\ -1 & 0 \end{bmatrix}$ and $\begin{bmatrix} 3 & -5 \\ 2 & 1 \end{bmatrix}$

b. $\begin{bmatrix} 5 \end{bmatrix}$ and $\begin{bmatrix} -3 \end{bmatrix}$

c. $\begin{bmatrix} 1&2\\3&4\\5&6 \end{bmatrix}$ and $\begin{bmatrix} 2&4\\6&8\\10&12 \end{bmatrix}$

d. $\begin{bmatrix} 1 & 2 \end{bmatrix}$ and $\begin{bmatrix} 1\\3 \end{bmatrix}$

e. $\begin{bmatrix} 1\\2 \end{bmatrix}$ and $\begin{bmatrix} 1\\3 \end{bmatrix}$ and $\begin{bmatrix} 2\\5 \end{bmatrix}$

```{solution} matrix-addition-ex1
:class: dropdown

a. $\begin{bmatrix} 1 & 2 \\ -1 & 0 \end{bmatrix} + \begin{bmatrix} 3 & -5 \\ 2 & 1 \end{bmatrix} = \bm 1+3&2-5\\-1+2&0+1 \em = \bm 4&-3\\1&1 \em$

b. $\begin{bmatrix} 5 \end{bmatrix} + \begin{bmatrix} -3 \end{bmatrix} = \bm 5 -3 \em = \bm -2 \em$

c. $\begin{bmatrix} 1&2\\3&4\\5&6 \end{bmatrix} + \begin{bmatrix} 2&4\\6&8\\10&12 \end{bmatrix} = \bm 1 + 2 & 2 + 4\\ 3 + 6 & 4 + 8\\5 + 10& 6 + 12 \em = \bm 3&6\\9&12\\15&18 \em$

d. They can't be added. The left matrix is a 1-by-2 matrix, whereas the right matrix is a 2-by-1 matrix, meaning they have different dimensions. 

e. $\begin{bmatrix} 1\\2 \end{bmatrix} + \begin{bmatrix} 1\\3 \end{bmatrix} + \begin{bmatrix} 2\\5 \end{bmatrix} = \bm 1 + 1 + 2 \\ 2 + 3 + 5 \em = \bm 4 \\ 10 \em$

```
````

In [2]:
## Matrix addition

B = np.array([[2, 4, 6],
             [8, 10, 12]])
add = A + B # adding two matrices
# this is a 1-D array of size 3 in python, which is different than the column-vector c created above
vec = np.array([-1, -2, 3]) 
# notice the difference how 1-D arrays add to 2-D arrays in python. # Try A+c and observe what happens
add_vec = A + vec 
add_vec

array([[0, 0, 6],
       [3, 3, 9]])

### Scalar multiplication
A _scalar_ is a fancy name for an ordinary number.  For now, we restrict ourselves to scalars, vectors, and matrices with _real_ entries, but we will eventually extend these ideas to complex numbers and matrices with complex entries.  Although technically not the same thing, we will treat the $1 \times 1$ matrix $[c]$ and the scalar $c \in \R$ as a scalar,[^notation] that is to say as an ordinary number, so we will drop the brackets. _Scalar multiplication_ takes a scalar $c$ and an $m \times n$ matrix $A$ an computes the $m \times n$ matrix $B = cA$ by multiplying each entry of $A$ by $c$.  For example:
$$
c = 3, \quad A = \bm 1 & 2 \\ -1 & 0 \em, \quad cA = 3\bm 1 & 2 \\ -1 & 0 \em=\bm 3 & 6 \\ -3 & 0\em.
$$
In general, if $B = cA$, then $b_{ij}=ca_{ij}$ for each entry $i=1,\dots,m$ and $j=1,\dots,n$.

[^notation]: Remember that we write $x \in S$ to mean that the element $x$ lives in the set $S$.  In this example, $c \in \R$ means that the element $c$ lives in the real line $\R$, and hence $c$ is a scalar.

````{exercise}  Scalar multiplication
:label: scalar-multiplication-ex1

For (a)-(e), compute the scalar-matrix product.

a. $5\bm 1 & 2 \\ 3 & 4\em$

b. $0\bm 1 & 1 \\ 2 & 3 \em$

c. $\frac 1 2 \bm 2 & 4 \\ 6 & 5 \em$

d. $\sqrt 2 \bm 1 & \sqrt 2 \\ 0 & \pi \em$

e. $i \bm 1 & i \\ -i & -1 \em$ where $i = \sqrt{-1}$

```{solution} scalar-multiplication-ex1
:class: dropdown

a. $5\bm 1 & 2 \\ 3 & 4\em = \bm 5\cdot 1 & 5\cdot 2 \\ 5\cdot 3 & 5\cdot 4\em = \bm 5 & 10 \\ 15 & 20\em$

b. $0\bm 1 & 1 \\ 2 & 3 \em = \bm 0\cdot 1 & 0\cdot 1 \\ 0\cdot 2 & 0\cdot 3 \em = \bm 0 & 0\\ 0 & 0\em$

c. $\frac 1 2 \bm 2 & 4 \\ 6 & 5 \em = \bm 2/2 & 4/2 \\ 6/2 & 5/2 \em = \bm 1 & 2 \\ 3 & 5/2 \em$

d. $\sqrt 2 \bm 1 & \sqrt 2 \\ 0 & \pi \em$

e. $i \bm 1 & i \\ -i & -1 \em = \bm i\cdot 1 & i\cdot i \\i \cdot -1 & i \cdot -i \em= \bm i & -1 \\1 & -i \em$

```
````

In [3]:
# scalar multiplication
scalar = 3
scalar_mult = scalar*A
scalar_mult
# Try vec*A and notice the difference

array([[ 3,  6,  9],
       [12, 15, 18]])

## Matrix multiplication warmup

We first look at multiplying a row vector with a column vector and use this as the base to multiply two matrices. Let $\vv a$ be a $1 \times n$ row vector and $\vv x$ be a $n \times 1$ column vector. The product $\vv a \vv x$ is defined as

\begin{equation}
\label{row_col_mul}
\vv a \vv x = \begin{bmatrix} a_1 & a_2 & \cdots & a_n\end{bmatrix}
\begin{bmatrix}
x_1 \\ x_2 \\ \vdots \\ x_n
\end{bmatrix} = a_1x_1 + a_2x_2 + \cdots a_nx_n = \sum_{k=1}^n a_kx_k
\end{equation}


````{exercise}  Vector products
:label: vector_prod_ex

For (a)-(b), multiply the two vectors. 

a. $ \bm 3 & 3\em, \bm 1 \\ 2\em$ 

b. $\bm 1 & \sqrt 2 \em, \bm 2 \\ \sqrt 2 \em$ 

```{solution} vector_prod_ex
:class: dropdown 

a. $\bm 3 & 3\em \bm 1 \\ 2\em = 3*1 + 3*2 = 9$ 

b. $\bm 1 & \sqrt 2 \em \bm 2 \\ \sqrt 2 \em = 1*2 + \sqrt 2 * \sqrt 2 = 4$ 
``` 
````


In [4]:
# vector products
b_c = np.array([[1], [2], [-1], [2]])
product = b @ b_c # multipying row-vector b with column-vector b_c
product

array([[3]])

## Matrix-Matrix multiplication

We can multiply two matrices $A, B$ if and only if they have compatible sizes. For example, to compute the product $C = AB$, $A$ must have the same number of columns as the number of rows in $B$. If $A$ is an $m \times n$ matrix and $B$ is an $n \times p$ matrix, then $C = AB$ is an $m \times p$ matrix, where each element is defined by
$$
c_{ij} = \sum_{k=1}^na_{ik}b_{kj} 
$$
The $(i, j)^{th}$ entry of $C$ is the vector product of the $i^{th}$ row of $A$ and $j^{th}$ column of $B$. 

An important special case of matrix-matrix multiplication is _matrix-vector products_. Let $\vv x$ be an $n \times 1$ column vector. Then, the matrix-vector product $\vv b = A \vv x$ is an $m\times 1$ column vector, where the entries of $\vv b$ are
$$
b_{i} = \sum_{k=1}^na_{ik}x_{i} 
$$

```{note}
Since $\vv b$ and $\vv x$ are column vectors, we only have the first index $i$ since the second index $j$ is always $1$.
```

Another way to do matrix multiplication is given below using matrix-vector products, which could be useful in many cases.

````{prf:definition}
:label: matmul-def1

If A is an $m \times n$ matrix, and if $B$ is an $n \times p$ matrix with columns $\vv b_1,\dots,\vv b_p$, then the matrix product $AB$ is then the $m \times p$ matrix whose columns are $A\vv b_1, A\vv b_2,\dots, A\vv b_p$, that is,
```{math}
:label: matmul-def
C = AB = A\bm \vv b_1 & \vv b_2 & \cdots & \vv b_p\em = \bm A\vv b_1 & A\vv b_2 & \cdots & A\vv b_p\em.
```
The $k^{th}$ column of $C$ is the matrix-vector product of $A$ and the $k^{th}$ column of $B$.
````

If we let $\vv a_1, \vv a_2, \cdots, \vv a_n$ to be the columns of $A$ so that 
$$
A = \bm \vv a_1 & \vv a_2 & \cdots & \vv a_n \em,
$$
then, another formula for $\vv b = A \vv x$ is
$$
\vv b = x_1 \vv a_1 + x_2 \vv a_2 + \cdots + x_n \vv a_n,
$$
that is, $\vv b$ is computed by adding the columns of $A$ weighted by the entries of $\vv x$. This will be useful later when we discuss about the _column span of a matrix_ $A$.   

### Special matrices

```{prf:definition}
:label: identity
The _identity matrix $I = I_m$_ is the $m \times m$ matrix
$$
I_m = \bm 
1 & 0 & 0 & \cdots & 0 & 0 \\
0 & 1 & 0 & \cdots & 0 & 0 \\
0 & 0 & 1 & \cdots & 0 & 0 \\
\vdots & \vdots & \vdots & \ddots & \vdots & \vdots \\
0 & 0 & 0 & \cdots & 1 & 0 \\
0 & 0 & 0 & \cdots & 0 & 1
\em.
$$
The entries along the _main diagonal_ which runs from top left to bottom right are all equal to 1 ($I_{ii} = 1$), and all other entries are equal to 0 $I_{ij} = 0$ for all $i \neq j$.  The identify matrix satisfies $IA = AI = A$. The $I$ that multiplies $A$ to the left and right might be of different sizes if $A$ is not square.
```

```{prf:definition}
:label: zero
The _zero matrix $O = O_{m \times n}$_ is the $m \times n$ matrix where all the entries is zero. The zero matrix satisfies $OA = AO = O$ with appropriate dimensions for $O$.
```

## Matrix arithmetic rules

```{image} ../figures/02-matrix_arithmetic.png
:label: mat_ar_rules
:alt: Matrix arithmetic rules!
:width: 600px
:align: center
```

```{warning} Matrix Multiplication is *NOT* Commutative
The left-to-right order in matrix products is critical because $AB$ and $BA$ are usually not the same.  In fact, unless $A$ and $B$ are both square matrices, only one of $AB$ or $BA$ will even be defined.  Given what we've seen so far, this shouldn't be surprising: the columns of $AB$ are linear combinations of the columns of $A$, whereas the columns of $BA$ are constructed from the columns of $B$.  We emphasize the position of the factors in the product $AB$ by saying $A$ is _right-multiplied_ by $B$ or that $B$ is _left-multiplied_ by $A$.  If $AB=BA$, we say that $A$ and $B$ _commute_ with each other.
```

```{warning} Cancellation Laws *DO NOT* hold
If $AB = AC$, then it is _not_ true in genereal that $B=C$
```
```{warning} $AB=0$
If the product $AB$ is the zero matrix, you _cannot_ conclude in general that either $A=0$ or $B=0$.
```

```{tip} Sizes
In matrix multiplication $A_{\color{green}{m} \times \color{red}{n}} B_{\color{red}{n} \times \color{green}{p}} = C_{\color{green}{m \times p}}$, the inner dimension $\color{red}{n}$ must match and cancel each other, while the outer dimensions $\color{green}{m, p}$ survive.
```

````{exercise}  Matrix Multiplication
:label: matrix-multiplication-ex1 

For (a)-(c), simplify the expressions if they exist; otherwise, indicate that the product doesn't exist.

$A = \bm 1 & 1 \\ 1 & 0 \em, B = \bm 2 & 4 & 1 \\ 0 & 3 & -1 \em, \vv x = \bm 13\\ 8 \\ 2\em, \vv y = \bm 1 & 2\em$

a.  $AB, BA$

b.  $B \vv x$

c.  $\vv y B, \vv y B \vv x$

```{solution} matrix-multiplication-ex1 
:class: dropdown 

a. $ BA$  does not exist, since sizes $2 \times 3$ and $2 \times 2$ do not match. 
 $$
 AB = \bm 1 & 1 \\ 1 & 0 \em \bm 2 & 4 & 1 \\ 0 & 3 & -1 \em  = \bm 1*2 + 1*0 & 1*4 + 1*3 & 1*1 + 1*-1\\ 1*2 + 0*0 & 1*4 + 0*3 & 1*1 + 0*-1\em = \bm 2 & 7 & 0 \\ 2 & 4 & 1 \em
 $$

b. $
\bm 2 & 4 & 1 \\ 0 & 3 & -1 \em\bm 13\\ 8 \\ 2\em = 13\bm 2 \\ 0 \em + 8\bm 4 \\ 3\em + 2\bm 1 \\ -1 \em= \bm 60 \\ 22 \em
$

c. $\vv y B = \bm 1 & 2\em \bm 2 & 4 & 1 \\ 0 & 3 & -1 \em = 1\bm 2 & 4 & 1 \em + 2 \bm 0 & 3 & -1 \em = \bm 2 & 10 & -1 \em $
$$
\vv y B \vv x = \bm 2 & 10 & -1 \em \bm 13\\ 8 \\ 2\em = 2*13 + 10*8 + -1*2 = 104
$$

``` 
````

In [5]:
# Matrix-vector with old A, c
product = A @ c # multipying matrix A with column-vector c
print("product: \n", product)
# Try A @ vec and notice the difference in the size of the result

# matrix vector multiplication for above exercises
A = np.array([[1, 1],
              [1, 0]])
B = np.array([[2, 4, 1],
              [0, 3, -1]])
x = np.array([[13],
              [8],
              [2]])
y = np.array([[1, 2]])



a_r = A@B
b_r = B@x
c_r = y@B
c_r1 = y@B@x
print("\nAB: \n", a_r, "\nBx: \n", b_r, "\nyB: \n", c_r, "\nyBx: \n", c_r1)

product: 
 [[ 8]
 [17]]

AB: 
 [[2 7 0]
 [2 4 1]] 
Bx: 
 [[60]
 [22]] 
yB: 
 [[ 2 10 -1]] 
yBx: 
 [[104]]


````{exercise}  Writing linear systems in matrix-vector notation
:label: matrix-vector-notation-ex1 

Write the following system of linear equations in matrix-vector notation:

\begin{align*}
2x + 3y - z + 4w &= 10 \\
3x - 2y + 5z - w &= 5 \\
x + 4y - 3z + 2w &= -3 \\
\end{align*}

```{solution} matrix-vector-notation-ex1 
:class: dropdown 

The corresponding linear system is:

\begin{align*}
    \bm 2 & 3 & -1 & 4 \\3 & -2 & 5 & -1 \\1 & 4 & -3 & 2 \\ \em\bm x \\y \\z \\w \\\em =\bm 10 \\5 \\-3 \\\em
\end{align*}

``` 
````

## Linear Systems in Matrix-Vector Notation
A general linear system of $m$ equations in $n$ unknowns takes the form
\begin{equation}
\label{gen-linsys}
\begin{array}{cccl}
a_{11} x_1 + a_{12} x_2 +& \cdots &+ a_{1n} x_n  = & b_1,\\
a_{21} x_1 + a_{22} x_2 +& \cdots &+ a_{2n} x_n  = & b_2,\\
\vdots & \vdots && \vdots \\
a_{m1} x_1 + a_{m2} x_2 +& \cdots &+ a_{mn} x_n  = & b_m,\\
\end{array}
\end{equation}
which we rewrite compactly as
```{math}
:label: matvec-eq
A \vv x = \vv b.
```
Equation [](#matvec-eq) is composed of three basic ingredients: the $m \times n$ _coefficient matrix_ $A$, with entries $a_{ij}$ as in [](#matrix), the column vector $\vv x = \begin{bmatrix} x_1 \\ x_2 \\ \vdots \\ x_n\end{bmatrix}$ containing the _unknowns_ or _variables_ and the column vector $\vv b = \begin{bmatrix} b_1 \\ b_2 \\ \vdots \\ b_m \end{bmatrix}$ containing the _right-hand sides_.  As you can see, it is a bit unwieldy to write column vectors inline, and so we will often equivalently write them as $\vv x = (x_1, x_2, \cdots, x_n)$ and $\vv b = (b_1, b_2, \cdots, b_m)$ instead.

```{warning}
Both $(1,2,3)$ and $\begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}$ represent the same $3 \times 1$ column vector.  However, $\begin{bmatrix} 1 & 2 & 3 \end{bmatrix}$ is a _different_ $1 \times 3$ row vector!  $(1,2,3)$ is understood to be a column vector because of the round brackets and the commas, whereas $\begin{bmatrix} 1 & 2 & 3 \end{bmatrix}$ is understood to be a row vector because of the square brackets and no commas.  It's a bit tricky, but you'll get used to it in no time!
```

Revisiting linear system [](./021-linsys-gauss.ipynb#simple-linsys00), we see that the coefficient matrix $A$, the unknown vector $\vv x$, and the right hand side vector $\vv b$ can be read off as
$$
A = \begin{bmatrix} 1 & 2 & 1 \\
2 & 6 & 1 \\
1 & 1 & 4 \end{bmatrix}, \quad \vv x = \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix}, \quad \vv b = \begin{bmatrix} 2 \\ 7 \\ 3 \end{bmatrix}.
$$

If a variable doesn't appear in an equation, then the corresponding matrix entry is 0.


```{prf:example} Matrix Multiplication Cautions

1. Here, we'll give some examples of when matrices don't commute:

\begin{align*}
\bm 1 & 2 \\3 & 4 \em \bm 2 & 0 \\1 & 2 \em 
= \bm  4 &4 \\10& 8\em
\neq 
\bm  2 &4 \\ 7&  10 \em= 
\bm 2 & 0 \\ 1 & 2 \em \bm 1 & 2 \\ 3 & 4\em
\end{align*}

It can also be the case that only one of the products exists. For example, the column vector $(0, 1, 2)$ and the row vector $\bm 3 &4\em$.

As an additional exercise, can you think of some specific examples of when matrices *do* commute? For example, $AB = BA$ if $A = I$ or $B = I$.

2. Here, we'll give an example of when the cancellation law doesn't hold (i.e., $AB = AC$ *does not* in general imply that $B = C$):

\begin{align*}
    \bm 0 & 1 \\ 0 & 1 \em \bm 0 & 1 \\ 0 & 1 \em = \bm 0 & 1 \\ 0 & 1 \em
\end{align*}

and 

\begin{align*}
    \bm 0 & 1 \\ 0 & 1 \em\bm 1 & 0 \\ 0 & 1 \em  = \bm 0 & 1 \\ 0 & 1 \em
\end{align*}

but of course,

\begin{align*}
    \bm 1 & 0 \\ 0 & 1 \em \neq \bm 0 & 1 \\ 0 & 1 \em 
\end{align*}

3. Here, we'll show that the product of 2 nonzero matrices can be zero:

\begin{align*}
    \bm 0& 1 \\ 0 & 0\em^2 = \bm 0& 1 \\ 0 & 0\em\bm 0& 1 \\ 0 & 0\em = \bm 0& 0 \\ 0 & 0\em
\end{align*}


```