---
title: Matrix inverses
subject:  Linear Algebraic Systems
subtitle: reciprocal of matrices
short_title: Matrix inverses
authors:
  - name: Nikolai Matni
    affiliations:
      - Dept. of Electrical and Systems Engineering
      - University of Pennsylvania
    email: nmatni@seas.upenn.edu
license: CC-BY-4.0
keywords: inverse, Gauss Jordan elimination, identity matrix
math:
  '\vv': '\mathbf{#1}'
  '\bm': '\begin{bmatrix}'
  '\em': '\end{bmatrix}'
  '\R': '\mathbb{R}'
---

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/nikolaimatni/ese-2030/HEAD?labpath=/00_Linear_Algebraic_Systems/025-linsys-inverses.ipynb)

{doc}`Lecture notes <../lecture_notes/Lecture 02 - Pivots + Permutations, Matrix Inverses (Gauss-Jordan), Transposes, Symmetric Matrices, and General Linear Systems.pdf>`

## Reading
Material related to this page, as well as additional exercises, can be found in ALA Ch. 1.5, LAA Ch 2.2.  These notes are mostly based on ALA Ch 1.5.

## Learning Objectives

By the end of this page, you should know:
- what is the inverse of a matrix
- computing inverse for 2x2 matrices
- important properties of matrix inverse: existence, product
- Gauss Jordan elimination to compute inverses

## Basic definition

The inverse of a matrix is analogous to the reciprocal $a^{−1} =\frac{1}{a}$ of a nonzero scalar $a \neq 0$. We already encountered the inverses of matrices corresponding to elementary row operations. In this section, we will study inverses of general square matrices. We begin with the formal definition.

```{prf:definition} Matrix inverse
:label: inverse
Let $A$ be a square matrix of size $n \times n$. An  $n \times n$ matrix $X$ is called the inverse of $A$ if it satisfies
$$
X A = I = A X,
$$
where $I = I_n$ is the $n \times n$ identity matrix. The inverse of $A$ is commonly denoted by $A^{−1}$.
```

```{warning}
Every square matrix does not necessarily have an inverse, just like every scalar does not have an inverse: $0^{-1} = \frac{1}{0}$ is not defined since $0x = 1$ has no solution.
```
```{warning}
In general, there is no straightforward way to guess the entries of $A^{-1}$ by looking at the entries of $A$.
```

## Formula for 2x2 matrices

We want to find the inverse of the matrix $A$, that is denoted by $X$

$$
A = \begin{bmatrix}
a & b \\ c & d
\end{bmatrix}, X = \begin{bmatrix}
x & y \\ z & w
 \end{bmatrix} \Rightarrow AX = I = \begin{bmatrix}
1 & 0 \\ 0 & 1
 \end{bmatrix}
$$
The above matrix equation will produce a set of four linear equations for each entry in $I$, where the unknowns are $(x, y, z, w)$. Solving by Gaussian Elimination, we get
\begin{equation}
\label{inv_2x2}
x = \frac{d}{ad-bc}, \ y = \frac{-b}{ad-bc}, \ z = \frac{-c}{ad-bc}, \ w = \frac{a}{ad-bc} \Rightarrow X = \frac{1}{ad-bc}\begin{bmatrix}
d & -b \\ -c & a
 \end{bmatrix}
\end{equation}
You can verify that $XA = I$ also holds. 
```{warning}
The inverse of $A$ exists if and only if $ad-bc \neq0$.
```

## Some useful properties

```{tip}
The inverse of a matrix $A$ reverses the changes $A$ does to a vector $\textbf{x}$ via matrix-vector multiplication. 
$$
\textbf{x} \xrightarrow{A} A \textbf{x} \xrightarrow{A^{-1}} A^{-1}A\textbf{x} = \textbf{x}
$$
```

For example, the elementary operation of adding twice the first row to the third row is given by 

$$
E = \begin{bmatrix}1 & 0 & 0 \\ 0 & 1 & 0 \\ 2 & 0 & 1 \end{bmatrix},
$$
while the inverse operation is given by
$$
L = \begin{bmatrix}1 & 0 & 0 \\ 0 & 1 & 0 \\ -2 & 0 & 1 \end{bmatrix},
$$
and you can verify that $L = E^{-1}$. You can also verify similarly for permutation matrices with exactly one interchange 
$$
P = \begin{bmatrix} 0 & 1 & 0 \\ 1 & 0 & 0 \\ 0 & 0 & 1 \end{bmatrix} = P^{-1}.
$$

```{important}
A square matrix has an inverse if and only if it is nonsingular
```

The above statement will be proved later, but for now think about the scalar analogy. The equation $ax=b$ has a unique solution $x = a^{-1}b$ if and only if $a \neq 0$. Similarly, $A \textbf{x} = \textbf{b}$ has a unique solution $\textbf{x} = A^{-1}\textbf{b}$ if and only if $A^{-1}$ exists.

```{note} Properties
1. The inverse of a square matrix, if it exists, is unique.
2. If $A$ is invertible, so is $A^{-1}$ and $\left(A^{-1}\right)^{-1} = A$.
3. If $A$ and $B$ are invertible matrices of the same size, then their product $AB$ is also invertible, and
$$
(AB)^{-1} = B^{-1}A^{-1} \\ \textbf{order is reversed!}
$$
We have to undo transformations in the right order.
$$
\textbf{x} \xrightarrow{B} B \textbf{x} \xrightarrow{A} AB\textbf{x} \xrightarrow{A^{-1}} A^{-1}AB\textbf{x} = B\textbf{x} \xrightarrow{B^{-1}} B^{-1}B\textbf{x} = \textbf{x}
$$
```

````{exercise}  Matrix inverses
:label: inverses-ex1

For each of the following inveritble matrices, find their inverse.

a. $\bm 1&2\\3&4 \em$

b. $\bm 1 & 0 & 0 \\ 0 & 2 & 0 \\ 0 & 0 & -3 \em$

c. $I_n$ (the identity matrix in $n$ dimensions)

d. $\bm 1&2&0\\0&1&2\\0&0&1 \em$

:::{hint} Click me for a hint!
:class: dropdown

a. Use the formula for $2\times 2$ matrices!

b. The inverse of this matrix will be another diagonal matrix (has zeros on off diagonal entries).

c. Can you find any (square) matrix $X$ such $I_nX = I_n$?

:::

```{solution} inverses-ex1
:class: dropdown

a. Using the formula for inverses of $2 \times 2$ matrices,

\begin{align*}
    \bm 1&2\\3&4 \em^{-1} = \frac{1}{1\cdot 4 - 2 \cdot 3}\bm 4 & -2 \\ -3 & 1\em = \bm -2 & 1 \\ \frac 3 2 & -\frac 1 2\em
\end{align*}

b. We can confirm that 

\begin{align*}
\bm 1 & 0 & 0 \\ 0 & 2 & 0 \\ 0 & 0 & -3 \em\bm 1 & 0 & 0 \\ 0 & \frac 1 2 & 0 \\ 0 & 0 & -\frac 1 3 \em = \bm 1&0&0\\0&1&0\\0&0&1 \em = \bm 1 & 0 & 0 \\ 0 & \frac 1 2 & 0 \\ 0 & 0 & -\frac 1 3 \em\bm 1 & 0 & 0 \\ 0 & 2 & 0 \\ 0 & 0 & -3 \em
\end{align*}

which means that 

\begin{align*}
\bm 1 & 0 & 0 \\ 0 & 2 & 0 \\ 0 & 0 & -3 \em^{-1} = \bm 1 & 0 & 0 \\ 0 & \frac 1 2 & 0 \\ 0 & 0 & -\frac 1 3 \em
\end{align*}

c. Remember that $I_n \times I_n = I_n$, which means $I_n^{-1} = I_n$.

```
````

````{exercise}  Inverse of a product of (invertible) matrices
:label: inverses-ex2

Given matrices 

\begin{align*}
    A = \bm 1&2\\3&4 \em, \quad B = \bm 1&1\\2&3 \em
\end{align*}

Find $A^{-1}$, $B^{-1}$, and $(AB)^{-1}$. Check that $(AB)^{-1} = B^{-1}A^{-1}$.

```{solution} inverses-ex2
:class: dropdown

Multiplying out $AB$, we get that

\begin{align*}
    AB = \bm 5&7\\11&15 \em 
\end{align*}

Using the formula for inverse of $2\times 2$ matrices, we get that

\begin{align*}
    A^{-1} = \bm -2&1\\ \frac 3 2 & -\frac 1 2 \em,\quad B^{-1} = \bm 3 & -1\\ -2 & 1 \em, \quad (AB)^{-1} = \bm -\frac {15} 2 & \frac 7 2 \\ \frac{ 11} 2 & -\frac 5 2 \em
\end{align*}

Finally, we check that $B^{-1}A^{-1} = (AB)^{-1}$:

\begin{align*}
    B^{-1}A^{-1} = \bm 3 & -1\\ -2 & 1 \em\bm -2&1\\ \frac 3 2 & -\frac 1 2 \em = \bm -\frac {15} 2 & \frac 7 2 \\ \frac{ 11} 2 & -\frac 5 2 \em = (AB)^{-1}
\end{align*}

Looks good!

```
````

In [1]:
# Matrix inverse

import numpy as np
from scipy.linalg import lu

A_2 = np.array([[1, 2],
              [0, -1]])

A = np.array([[1, 2, 0],
              [0, 1, 0],
              [0, -3, 1]])

A_2_inv = np.linalg.inv(A_2)
A_inv = np.linalg.inv(A)
print("A_2_inv: \n", A_2_inv, "\nA_inv: \n", A_inv)
print("\nChecking inverses: \n", A_2_inv @ A_2, "\n", A @ A_inv)

A_2_inv: 
 [[ 1.  2.]
 [-0. -1.]] 
A_inv: 
 [[ 1. -2.  0.]
 [-0.  1. -0.]
 [ 0.  3.  1.]]

Checking inverses: 
 [[1. 0.]
 [0. 1.]] 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
# Inverse of the product

B = np.array([[1, 2, 0],
              [0, 3, 0],
              [1, -3, 1]])

B_inv = np.linalg.inv(B)

AB_inv = np.linalg.inv(A@B)
print("\nInverse of product: \n", AB_inv, "\nProduct of inverses:\n", B_inv @ A_inv)


Inverse of product: 
 [[ 1.         -2.66666667  0.        ]
 [-0.          0.33333333 -0.        ]
 [-1.          6.66666667  1.        ]] 
Product of inverses:
 [[ 1.         -2.66666667  0.        ]
 [ 0.          0.33333333  0.        ]
 [-1.          6.66666667  1.        ]]


## Gauss Jordan Elimination

Gauss Jordan Elimination (GJE) is the principal algorithm for computing inverses of a nonsingular matrix. 

```{important}
For a square matrix $A$, we only need to solve the _right inverse_ $AX = I$, since the _left inverse_ $XA = I$ is an automatic consequence.
```

```{note}
Some matrices may satsify only one of the two conditions: either a right inverse $AX = I$ or a left inverse $XA = I$. For a non-square matrix, the same $X$ cannot satisfy $AX = XA = I$ (check dimensions). Hence, we emphasize that for $X$ to be an inverse of $A$, both left and right inverse conditions should be satisfied. 
```

We focus on the identity matrix which is the result after multiplying a matrix with its inverse. We define the $n \times 1$ _unit vectors_ $\textbf{e}_i$:
$$
\textbf{e}_1 = \begin{bmatrix} 1 \\ 0 \\ 0 \\ \vdots \\ 0 \end{bmatrix}, \ \textbf{e}_2 = \begin{bmatrix} 0 \\ 1 \\ 0 \\ \vdots \\ 0 \end{bmatrix}, \cdots, \ \textbf{e}_n = \begin{bmatrix} 0 \\ 0 \\ \vdots \\ 1 \end{bmatrix}
$$
as the vectors with exactly one entry of $1$ in the $i^{th}$ position and zeros elsewhere. The vectors $\textbf{e}_i$ are the columns of the identity matrix $I_n$:
$$
I_n = \begin{bmatrix} \textbf{e}_1 & \textbf{e}_2 & \cdots & \textbf{e}_n \end{bmatrix}
$$
Hence, the right inverse equation can be written as
$$
AX = I \Leftrightarrow A \begin{bmatrix} \textbf{x}_1 & \textbf{x}_2 & \cdots & \textbf{x}_n \end{bmatrix} = \begin{bmatrix} \textbf{e}_1 & \textbf{e}_2 & \cdots & \textbf{e}_n \end{bmatrix} \Leftrightarrow A\textbf{x}_1 = \textbf{e}_1, A\textbf{x}_2 = \textbf{e}_2, \cdots, A\textbf{x}_n = \textbf{e}_n
$$

The above set of $n$ linear system of equations have the same coefficient matrix $A$ and hence we can construct the following large augmented matrix $M$.
\begin{equation}
\label{big_augm}
M = \left[ \begin{array}{c|ccc} A & \textbf{e}_1 & \textbf{e}_2 & \cdots & \textbf{e}_n  \end{array}\right] = \left[ \begin{array}{c|c} A & I  \end{array}\right].
\end{equation}

Applying row operations ([scaling and adding](./023-linsys-gauuss.ipynb#rowop1), [swapping](./024-linsys-perms.ipynb#rowop2)) to [](#big_augm), we can reduce to upper triangular form
$$
M = \left[ \begin{array}{c|c} A & I  \end{array}\right] \leftrightarrow N = \left[ \begin{array}{c|c} U & C  \end{array}\right].
$$
Then, we can solve the below set of $n$ linear systems via back substitution.
$$
U\textbf{x}_1 = \textbf{c}_1, U\textbf{x}_2 = \textbf{c}_2, \cdots, U\textbf{x}_n = \textbf{c}_n
$$

For example, consider the following $A$ matrix and the corresponding upper triangular form
\begin{equation}
\label{U_I}
A = \begin{bmatrix}0 & 2 & 1 \\ 2 & 6 & 1 \\ 1 & 1 & 4 \end{bmatrix} \Rightarrow M =  
\left[ \begin{array}{ccc|ccc} 0 & 2 & 1 & 1 & 0 & 0 \\ 2 & 6 & 1 & 0 & 1 & 0 \\ 1 & 1 & 4 & 0 & 0 & 1 \end{array}\right] \leftrightarrow N = \left[ \begin{array}{ccc|ccc} 2 & 6 & 1 & 0 & 1 & 0 \\ 0 & 2 & 1 & 1 & 0 & 0 \\ 0 & 0 & \frac{9}{2} & 1 & -\frac{1}{2} & 1 \end{array}\right].
\end{equation}
A mot common version of GJE continues to apply row operations and fully reduce the augmented matrix to the form $\left[ \begin{array}{c|c} I & X  \end{array}\right]$ so that $X$ is the inverse of $A$. However, in our current form $\left[ \begin{array}{c|c} U & C  \end{array}\right] $, the diagonal pivots of $U$ are not $1$. 
```{prf:observation} Elementary Row Operation \#3
:label: rowop3
Multiplying a row of the augmented matrix by a nonzero scalar yields an equivalent linear system.
```
The [scaling operation](#rowop3) on $N$ in [](#U_I) reduces the augmented matrix to
\begin{equation}
\label{V}
N = \left[ \begin{array}{ccc|ccc} 2 & 6 & 1 & 0 & 1 & 0 \\ 0 & 2 & 1 & 1 & 0 & 0 \\ 0 & 0 & \frac{9}{2} & 1 & -\frac{1}{2} & 1 \end{array}\right] \leftrightarrow \left[ \begin{array}{c|c} V & B \end{array}\right] = \left[ \begin{array}{ccc|ccc} 1 & 3 & \frac{1}{2} & 0 & \frac{1}{2} & 0 \\ 0 & 1 & \frac{1}{2} & \frac{1}{2} & 0 & 0 \\ 0 & 0 & 1 & \frac{2}{9} & -\frac{1}{9} & \frac{2}{9} \end{array}\right],
\end{equation}

where we divide each row by its corresponding pivot. Now, to make $V$ identity, we perform row operations starting from $(2, 3)$ since we need to make the upper triangular entries $0$.
\begin{equation}
\label{I_X}
\left[ \begin{array}{c|c} V & B \end{array}\right] = \left[ \begin{array}{ccc|ccc} 1 & 3 & \frac{1}{2} & 0 & \frac{1}{2} & 0 \\ 0 & 1 & \frac{1}{2} & \frac{1}{2} & 0 & 0 \\ 0 & 0 & 1 & \frac{2}{9} & -\frac{1}{9} & \frac{2}{9} \end{array}\right] \leftrightarrow \left[ \begin{array}{ccc|ccc} 1 & 0 & 0 & -\frac{23}{18} & \frac{7}{18} & \frac{2}{9} \\ 0 & 1 & 0 & \frac{7}{18} & \frac{1}{18} & -\frac{1}{9} \\ 0 & 0 & 1 & \frac{2}{9} & -\frac{1}{9} & \frac{2}{9} \end{array}\right]
\end{equation}
Finally, the right-hand matrix in [](#I_X) is the inverse of $A$:
$$
A^{-1} = \left[ \begin{array}{ccc}  -\frac{23}{18} & \frac{7}{18} & \frac{2}{9} \\  \frac{7}{18} & \frac{1}{18} & -\frac{1}{9} \\  \frac{2}{9} & -\frac{1}{9} & \frac{2}{9} \end{array}\right]
$$

:::{hint} Think!
:class: dropdown
What is the [elementary matrix](./023a-linsys-LU.ipynb#elementary) corresponding to the [scaling operation](#row-op3)? Start from the identity matrix as before.

````{exercise}  Gauss-Jordan Elimination
:label: inverses-ex3

Given the matrix

\begin{align*}
A = \bm 1&1&1 \\ 1&2&4 \\ 1&3&9 \em
\end{align*}

Find $A^{-1}$ using Gauss-Jordan elimination.

```{solution} inverses-ex3
:class: dropdown

Autmenting $A$ to the identity, we get

\begin{align*}
    \left[ \begin{array}{ccc|ccc} 
    1 & 1 & 1 &     1 & 0 & 0\\
    1 & 2 & 4 &     0 & 1 & 0\\
    1 & 3 & 9 &     0 & 0 & 1
    \end{array}\right]
\end{align*}

Using Row 1 to eliminate Column 1, we get

\begin{align*}
    \left[ \begin{array}{ccc|ccc} 
    1 & 1 & 1 &     1 & 0 & 0\\
    0 & 1 & 3 &     -1 & 1 & 0\\
    0 & 2 & 8 &     -1 & 0 & 1
    \end{array}\right]
\end{align*}

Using Row 2 to eliminate Column 2, we get

\begin{align*}
    \left[ \begin{array}{ccc|ccc} 
    1 & 0 & -2 &     2 & -1 & 0\\
    0 & 1 & 3 &     -1 & 1 & 0\\
    0 & 0 & 2 &     1 & -2 & 1
    \end{array}\right]
\end{align*}

Using Row 3 to eliminate Column 3, we get

\begin{align*}
    \left[ \begin{array}{ccc|ccc} 
    1 & 0 & 0 &     3 & -3 & 1\\
    0 & 1 & 0 &     -2.5 & 4 & -1.5\\
    0 & 0 & 2 &     1 & -2 & 1
    \end{array}\right]
\end{align*}

Scaling Row 3 so it's entry is one,

\begin{align*}
    \left[ \begin{array}{ccc|ccc} 
    1 & 0 & 0 &     3 & -3 & 1\\
    0 & 1 & 0 &     -2.5 & 4 & -1.5\\
    0 & 0 & 1 &     0.5 & -1 & 0.5
    \end{array}\right]
\end{align*}

Hence we have found that

\begin{align*}
    A^{-1} = \bm 3 & -3 & 1\\ -2.5 & 4 & -1.5\\0.5 & -1 & 0.5 \em
\end{align*}

```
````

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/nikolaimatni/ese-2030/HEAD?labpath=/00_Linear_Algebraic_Systems/025-linsys-inverses.ipynb)
