---
title: Modeling Network Flow using Systems of Equations
subject: Applied Linear Algebra
subtitle: Interactive and responsive lecture notes
short_title: Modeling Network FLow
authors:
  - name: Renukanandan Tumu
    affiliations:
      - Dept. of Electrical and Systems Engineering
      - University of Pennsylvania
    email: nandant@seas.upenn.edu
license: CC-BY-4.0
keywords: sample notes, ese 2030, linear algebra
abstract: |
    This page previews some of the functionality of this online textbook.  Don't be afraid to click, hover over, and otherwise explore the contents of this page.  And don't worry, whenever we come across a new functionality in the main text for the first time, we'll remind you how to use it.
---

## What is network flow?

We can think about network flow as the flow of traffic through a road network, or water through a grid of pipes. 
In this section, we will try to answer questions about how much traffic or water moved through specific links in our network, and think about what would happen if we were to modify or delete those links.
A key assumption we will make is one of conservation. In the figure below, this means that $x_1+x_2 = 30$

```{image} 02-net-flow.png
:alt: Network Flow
:width: 250px
:align: center
```

## What Linear Algebra tools do we need to model network flow?
### Concepts
1. Gaussian Elimination / Row Reduction


### Computation
1. Python
1. Numpy

## Small Example

```{image} 02-basic-network.png
:alt: Simple networks
:width: 300px
:align: center
```



> Adapted from LAA by Lay, Lay, and McDonald 

The system of equations that corresponds to this system is:

```{math}
:label: simple-system
\begin{align}
10 + 40 &= x_2 + x_4 \\
x_2 + x_3 &= x_1 + 30 \\
30 + 50 &= x_3 + x_5 \\
x_5 + x_4 &= 60
\end{align}
```
The equations model the flow in the intermediate nodes. We can represent this as the matrix below:

```{math}
\begin{bmatrix}
    0 & 1 & 0 & 1 & 0 & 50 \\
    -1 & 1 & 1 & 0 & 0 & 30 \\
    0 & 0 & 1 & 0 & 1 & 80 \\
    0 & 0 & 0 & 1 & 1 &  60 \\
\end{bmatrix}
```

In [6]:
import numpy as np
from numpy.linalg import lstsq
M = np.array([
    [0 , 1 , 0 , 1, 0, 50],
    [-1 , 1 , 1 , 0 , 0, 30],
    [1 , 0 , 1 , 0 , 1, 80],
    [0 , 0 , 0 , 1,   1, 60],
])
A = M[:,:-1]
B = M[:, -1]

In [10]:
x, residuals, rank, s = lstsq(A,B, rcond=None)

In [11]:
x

array([20. , 22.5, 27.5, 27.5, 32.5])

## Penn Engineering Road Network
```{image} 02-penn-roads.png
:alt: Penn Road Network
:width: 400px
:align: center
```


The above figure shows a road network that looks similar to that around Penn Engineering. We model these road networks the same way, by balancing the inflows and outflows of each node. This yields the following equations:

```{math}
\begin{align}
60 &= x_1 + x_4 \\
x_1 + x_5 &= x_2 \\ 
x_2 &= x_6 + x_3 \\ 
x_3 + x_7 = 80 \\

x_4 + x_8 &= 40 + x_{11} \\
x_9 + x_{10} &= x_8 + x_5 \\
x_{10} + x_6 &= x_{11} + x_9 \\
60 &= x_{10} + x_7 \\

80 + x_{11} &= x_{12} \\
x_{12} + x_{11} &= x_{10} + 80
\end{align}
```

This gives us the following matrix
```{math}
\begin{bmatrix}
    x_1 & x_2 & x_3 & x_4 & x_5 & x_6 & x_7 & x_8 & x_9 & x_{10} & x_{11} & x_{12} & C \\
    \hline
    1   & 0   & 0   & 1   & 0   & 0   & 0   & 0   & 0   & 0      & 0      & 0      & 60 \\
    1   & -1  & 0   & 0   & 1   & 0   & 0   & 0   & 0   & 0      & 0      & 0      & 0 \\
    0   & 1   & -1  & 0   & 0   & -1  & 0   & 0   & 0   & 0      & 0      & 0      & 0 \\
    0   & 0   & 1   & 0   & 0   & 0   & 1   & 0   & 0   & 0      & 0      & 0      & 80 \\

    0   & 0   & 0   & 1   & 0   & 0   & 0   & 1   & 0   & 0      & -1     & 0      & 40 \\
    0   & 0   & 0   & 0   & -1  & 0   & 0   & -1  & 1   & 1      & 0      & 0      & 0 \\
    0   & 0   & 0   & 0   & 0   & 1   & 0   & 0   & -1  & 1      & -1     & 0      & 0 \\
    0   & 0   & 0   & 0   & 0   & 0   & -1  & 0   & 0   & -1     & 0      & 0      & 60 \\

    0   & 0   & 0   & 0   & 0   & 0   & 0   & 0   & 0   & 0      & -1     & 1      & 80 \\
    0   & 0   & 0   & 0   & 0   & 0   & 0   & 0   & 0   & -1     & 1      & 1      & 80 \\
\end{bmatrix}
```

In [53]:
M = np.array(
    [
        [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 60],
        [1, -1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, -1, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 80],
        [0, 0, 0, 1, 0, 0, 0, 1, 0, 0, -1, 0, 40],
        [0, 0, 0, 0, -1, 0, 0, -1, 1, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, -1, 1, -1, 0, 0],
        [0, 0, 0, 0, 0, 0, -1, 0, 0, -1, 0, 0, 60],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 1, 80],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 1, 1, 80],
    ]
)
A = M[:,:-1]
B = M[:, -1]

In [54]:
x, residuals, rank, s = lstsq(A,B, rcond=-1)

In [55]:
x

array([ 45.84962406,  39.65413534,  60.5112782 ,  26.15037594,
       -18.19548872,  -8.85714286,   7.4887218 , -37.89473684,
       -12.60150376, -55.4887218 , -39.7443609 ,  52.2556391 ])

In [56]:
rank

9

Uh oh, this is weird, we can't have negative traffic flowing through the system! If we look at the rank of this matrix, it is only 9, even though we have 12 variables. We will learn later in the course that this means that there are infinite solutions to this system.

Let's try to get a more plausible solution by using a different solver, which prevents non-negative solutions.

In [65]:
from scipy.optimize import nnls
x = nnls(A,B)
x

(array([52.30769231, 61.53846154, 70.76923077, 16.92307692,  0.        ,
         0.        ,  0.        , 13.84615385,  4.61538462,  0.        ,
         0.        , 80.        ]),
 64.45033866354896)

## Modeling Road Closures
Let's see what happens if we have to shut down $x_4$ due to construction! What will the impact be on the network?

In [69]:
M = np.array(
    [
        [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 60],
        [1, -1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, -1, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 80],
        [0, 0, 0, 1, 0, 0, 0, 1, 0, 0, -1, 0, 40],
        [0, 0, 0, 0, -1, 0, 0, -1, 1, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, -1, 1, -1, 0, 0],
        [0, 0, 0, 0, 0, 0, -1, 0, 0, -1, 0, 0, 60],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 1, 80],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 1, 1, 80],

        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        # [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        # [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
    ]
)
A = M[:,:-1]
B = M[:, -1]

In [70]:
x, rnorm = nnls(A,B)

In [71]:
x

array([68.57142857, 77.14285714, 71.42857143,  0.        ,  0.        ,
       14.28571429,  0.        , 31.42857143, 22.85714286,  0.        ,
        0.        , 80.        ])

We can see that the traffic reflows around the closed link.